### ISSUE TITLE
Ajax error when adding widgets in groups

### ISSUE THREAD

**Issue by oseg** [ColdTrick/widget_manager#74] opened 2016-02-08 10:31 UTC
Regression introduced in plugin v5.2. The plugin was working fine with v5.1

Context: Elgg v1.12.4 (also reproduced in v1.12.7)

Widget manager settings for group:
  - Enable Widget manager for groups: Yes, manageable by group tool option
  - Widget management for groups default enable: Yes
  - Only administrator can enable  group widgets: No

Scenario:
  - logged as admin
  - Create a "test" group (default group settings)
  - Click on the "Add widgets" button
  - Add the "Content by tag" widget (for instance, but same issue with the other widgets: "Free HTML"...)

=> The "Unexpected error while performing an AJAX call. Maybe the connection to the server is lost" message error is displayed, and the widget is not added.

**Comment by jdalsem** [comment] 2016-02-09 09:40
Could this be caused by a javascript error on the page? Is javascript loaded completely (test by leaving a few seconds between the clicks... or look at the loader icon in the address bar of your browser).. at the moment i am unable to reproduce. Can you reproduce on a stock Elgg with only widgetmanager as a custom plugin??

**Comment by insideth** [comment] 2016-02-17 13:04
I´ve the issue too with Elgg 1.12.8 and WidgetManager 5.2

These are my logs:

`2016/02/17 14:02:33 [error] 884#884: *2115 FastCGI sent in stderr: "PHP message: Exception #1455714153: exception 'IOException' with message 'Failed to load new ElggObject for GUID: 373' in /home/www/redup_triploader_com/htdocs/engine/classes/ElggObject.php:80
Stack trace:
#0 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php(100): ElggObject->__construct(Object(stdClass))
#1 /home/www/redup_triploader_com/htdocs/engine/lib/entities.php(372): Elgg\Database\EntityTable->rowToElggStar(Object(stdClass))
#2 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php(660): entity_row_to_elggstar(Object(stdClass))
#3 /home/www/redup_triploader_com/htdocs/engine/lib/entities.php(509): Elgg\Database\EntityTable->fetchFromSql('SELECT DISTINCT...', NULL)
#4 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php(471): _elgg_fetch_entities_from_sql('SELECT DISTINCT...', NULL)
#5 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php(174): Elgg\Database\EntityTable->getEntiti...
PHP message: sending email to: insideth@gmail.com, ceo@insidethehotel.com" while reading response header from upstream, client: 192.168.56.101, server: local.redup.triploader.com, request: "POST /action/widgets/add HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "local.redup.triploader.com", referrer: "http://local.redup.triploader.com/groups/profile/214/madrid"
`

action/widgets/add exception dump:

`  Failed to load new ElggObject for GUID: 7736

        IOException Object
(
    [message:protected] =&gt; Failed to load new ElggObject for GUID: 7736
    [string:Exception:private] =&gt; exception &#039;IOException&#039; with message &#039;Failed to load new ElggObject for GUID: 7736&#039; in /home/www/redup_triploader_com/htdocs/engine/classes/ElggObject.php:80
Stack trace:
#0 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php(100): ElggObject-&gt;__construct(Object(stdClass))
#1 /home/www/redup_triploader_com/htdocs/engine/lib/entities.php(372): Elgg\Database\EntityTable-&gt;rowToElggStar(Object(stdClass))
#2 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php(660): entity_row_to_elggstar(Object(stdClass))
#3 /home/www/redup_triploader_com/htdocs/engine/lib/entities.php(509): Elgg\Database\EntityTable-&gt;fetchFromSql(&#039;SELECT DISTINCT...&#039;, NULL)
#4 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php(471): _elgg_fetch_entities_from_sql(&#039;SELECT DISTINCT...&#039;, NULL)
#5 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php(174): Elgg\Database\EntityTable-&gt;getEntities(Array)
#6 /home/www/redup_triploader_com/htdocs/engine/lib/entities.php(383): Elgg\Database\EntityTable-&gt;get(7736)
#7 /home/www/redup_triploader_com/htdocs/engine/classes/ElggEntity.php(1731): get_entity(7736)
#8 /home/www/redup_triploader_com/htdocs/engine/classes/ElggObject.php(159): ElggEntity-&gt;update()
#9 /home/www/redup_triploader_com/htdocs/engine/classes/ElggEntity.php(1590): ElggObject-&gt;update()
#10 /home/www/redup_triploader_com/htdocs/mod/widget_manager/lib/events.php(86): ElggEntity-&gt;save()
#11 [internal function]: widget_manager_create_object_handler(&#039;create&#039;, &#039;object&#039;, Object(ElggWidget))
#12 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/EventsService.php(56): call_user_func_array(&#039;widget_manager_...&#039;, Array)
#13 /home/www/redup_triploader_com/htdocs/engine/classes/ElggEntity.php(1594): Elgg\EventsService-&gt;trigger(&#039;create&#039;, &#039;object&#039;, Object(ElggWidget))
#14 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/WidgetsService.php(94): ElggEntity-&gt;save()
#15 /home/www/redup_triploader_com/htdocs/engine/lib/widgets.php(39): Elgg\WidgetsService-&gt;createWidget(508, &#039;content_by_tag&#039;, &#039;groups&#039;, NULL)
#16 /home/www/redup_triploader_com/htdocs/actions/widgets/add.php(27): elgg_create_widget(508, &#039;content_by_tag&#039;, &#039;groups&#039;)
#17 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/ActionsService.php(88): include(&#039;/home/www/redup...&#039;)
#18 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/ActionsService.php(70): Elgg\ActionsService::includeFile(&#039;/home/www/redup...&#039;)
#19 /home/www/redup_triploader_com/htdocs/engine/lib/actions.php(20): Elgg\ActionsService-&gt;execute(&#039;widgets/add&#039;)
#20 [internal function]: _elgg_action_handler(Array, &#039;action&#039;)
#21 /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Router.php(80): call_user_func(&#039;_elgg_action_ha...&#039;, Array, &#039;action&#039;)
#22 /home/www/redup_triploader_com/htdocs/index.php(63): Elgg\Router-&gt;route(Object(Elgg\Http\Request))
#23 {main}
    [code:protected] =&gt; 0
    [file:protected] =&gt; /home/www/redup_triploader_com/htdocs/engine/classes/ElggObject.php
    [line:protected] =&gt; 80
    [trace:Exception:private] =&gt; Array
        (
            [0] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php
                    [line] =&gt; 100
                    [function] =&gt; __construct
                    [class] =&gt; ElggObject
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; stdClass Object
                                (
                                    [guid] =&gt; 7736
                                    [type] =&gt; object
                                    [subtype] =&gt; 3
                                    [owner_guid] =&gt; 508
                                    [site_guid] =&gt; 1
                                    [container_guid] =&gt; 508
                                    [access_id] =&gt; 0
                                    [time_created] =&gt; 1455712949
                                    [time_updated] =&gt; 1455712949
                                    [last_action] =&gt; 1455712949
                                    [enabled] =&gt; yes
                                    [title] =&gt;
                                    [description] =&gt;
                                )

                        )

                )

            [1] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/engine/lib/entities.php
                    [line] =&gt; 372
                    [function] =&gt; rowToElggStar
                    [class] =&gt; Elgg\Database\EntityTable
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; stdClass Object
                                (
                                    [guid] =&gt; 7736
                                    [type] =&gt; object
                                    [subtype] =&gt; 3
                                    [owner_guid] =&gt; 508
                                    [site_guid] =&gt; 1
                                    [container_guid] =&gt; 508
                                    [access_id] =&gt; 0
                                    [time_created] =&gt; 1455712949
                                    [time_updated] =&gt; 1455712949
                                    [last_action] =&gt; 1455712949
                                    [enabled] =&gt; yes
                                    [title] =&gt;
                                    [description] =&gt;
                                )

                        )

                )

            [2] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php
                    [line] =&gt; 660
                    [function] =&gt; entity_row_to_elggstar
                    [args] =&gt; Array
                        (
                            [0] =&gt; stdClass Object
                                (
                                    [guid] =&gt; 7736
                                    [type] =&gt; object
                                    [subtype] =&gt; 3
                                    [owner_guid] =&gt; 508
                                    [site_guid] =&gt; 1
                                    [container_guid] =&gt; 508
                                    [access_id] =&gt; 0
                                    [time_created] =&gt; 1455712949
                                    [time_updated] =&gt; 1455712949
                                    [last_action] =&gt; 1455712949
                                    [enabled] =&gt; yes
                                    [title] =&gt;
                                    [description] =&gt;
                                )

                        )

                )

            [3] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/engine/lib/entities.php
                    [line] =&gt; 509
                    [function] =&gt; fetchFromSql
                    [class] =&gt; Elgg\Database\EntityTable
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; SELECT DISTINCT e.* FROM elgg_entities e  WHERE  (e.guid IN (7736)) AND ((1 = 1) AND (e.enabled = &#039;yes&#039;)) ORDER BY e.time_created desc LIMIT 0, 1
                            [1] =&gt;
                        )

                )

            [4] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php
                    [line] =&gt; 471
                    [function] =&gt; _elgg_fetch_entities_from_sql
                    [args] =&gt; Array
                        (
                            [0] =&gt; SELECT DISTINCT e.* FROM elgg_entities e  WHERE  (e.guid IN (7736)) AND ((1 = 1) AND (e.enabled = &#039;yes&#039;)) ORDER BY e.time_created desc LIMIT 0, 1
                            [1] =&gt;
                        )

                )

            [5] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/engine/classes/Elgg/Database/EntityTable.php
                    [line] =&gt; 174
                    [function] =&gt; getEntities
                    [class] =&gt; Elgg\Database\EntityTable
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; Array
                                (
                                    [guid] =&gt; 7736
                                    [limit] =&gt; 1
                                    [site_guids] =&gt;
                                )

                        )

                )

            [6] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/engine/lib/entities.php
                    [line] =&gt; 383
                    [function] =&gt; get
                    [class] =&gt; Elgg\Database\EntityTable
                    [type] =&gt; -&gt;
                    [args] =&gt; Array
                        (
                            [0] =&gt; 7736
                        )

                )

            [7] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/engine/classes/ElggEntity.php
                    [line] =&gt; 1731
                    [function] =&gt; get_entity
                    [args] =&gt; Array
                        (
                            [0] =&gt; 7736
                                            [time_created] =&gt; 1455712949
                                            [guid] =&gt; 7736
                                            [type] =&gt; object
                                            [subtype] =&gt; 3
                                            [owner_guid] =&gt; 508
                                            [container_guid] =&gt; 508
                                            [site_guid] =&gt; 1
                                            [access_id] =&gt; 50
                                            [time_updated] =&gt; 1455712949
                                            [last_action] =&gt; 1455712949
                                                    [time_created] =&gt; 1455712949
                                                    [guid] =&gt; 7736
                                                    [type] =&gt; object
                                                    [subtype] =&gt; 3
                                                    [owner_guid] =&gt; 508
                                                    [container_guid] =&gt; 508
                                                    [site_guid] =&gt; 1
                                                    [access_id] =&gt; 50
                                                    [time_updated] =&gt; 1455712949
                                                    [last_action] =&gt; 1455712949
                                            [time_created] =&gt; 1455712949
                                            [guid] =&gt; 7736
                                            [type] =&gt; object
                                            [subtype] =&gt; 3
                                            [owner_guid] =&gt; 508
                                            [container_guid] =&gt; 508
                                            [site_guid] =&gt; 1
                                            [access_id] =&gt; 50
                                            [time_updated] =&gt; 1455712949
                                            [last_action] =&gt; 1455712949
                            [0] =&gt; 508
                            [1] =&gt; content_by_tag
                            [2] =&gt; groups
                            [3] =&gt;
                        )

                )

            [16] =&gt; Array
                (
                    [file] =&gt; /home/www/redup_triploader_com/htdocs/actions/widgets/add.php
                    [line] =&gt; 27
                    [function] =&gt; elgg_create_widget
                    [args] =&gt; Array
                        (
                            [0] =&gt; 508
                            [1] =&gt; content_by_tag
                                                    [handler] =&gt; content_by_tag
                                                    [page_owner_guid] =&gt; 508
                                                    [context] =&gt; groups
                                                    [show_access] =&gt; 1
                                                    [default_widgets] =&gt; 0
                                                    [__elgg_ts] =&gt; 1455712938
                                                    [__elgg_token] =&gt; V3JVcRp8R9sRA8-mKpY0_g
                                                )

                                        )

                                    [query] =&gt; Symfony\Component\HttpFoundation\ParameterBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                    [__elgg_uri] =&gt; /action/widgets/add
                                                )

                                        )

                                    [server] =&gt; Symfony\Component\HttpFoundation\ServerBag Object
                                        (
                                            [parameters:protected] =&gt; Array
                                                (
                                                    [USER] =&gt; www-data
                                                    [HOME] =&gt; /var/www
                                                    [FCGI_ROLE] =&gt; RESPONDER
                                                    [SCRIPT_FILENAME] =&gt; /home/www/redup_triploader_com/htdocs/index.php
                                                    [QUERY_STRING] =&gt; __elgg_uri=/action/widgets/add&amp;
                                                    [REQUEST_METHOD] =&gt; POST
                                                    [CONTENT_TYPE] =&gt; application/x-www-form-urlencoded; charset=UTF-8
                                                    [CONTENT_LENGTH] =&gt; 146
                                                    [SCRIPT_NAME] =&gt; /index.php
                                                    [REQUEST_URI] =&gt; /action/widgets/add
                                                    [DOCUMENT_URI] =&gt; /index.php
                                                    [DOCUMENT_ROOT] =&gt; /home/www/redup_triploader_com/htdocs
                                                    [SERVER_PROTOCOL] =&gt; HTTP/1.1
                                                    [GATEWAY_INTERFACE] =&gt; CGI/1.1
                                                    [SERVER_SOFTWARE] =&gt; nginx/1.6.2
                                                    [REMOTE_ADDR] =&gt; 62.14.183.39
                                                    [REMOTE_PORT] =&gt; 54462
                                                    [SERVER_ADDR] =&gt; 172.31.16.4
                                                    [SERVER_PORT] =&gt; 80
                                                    [SERVER_NAME] =&gt; redup.triploader.com
                                                    [REDIRECT_STATUS] =&gt; 200
                                                    [HTTP_HOST] =&gt; redup.triploader.com
                                                    [HTTP_CONNECTION] =&gt; keep-alive
                                                    [HTTP_CONTENT_LENGTH] =&gt; 146
                                                    [HTTP_AUTHORIZATION] =&gt; Basic ZGV2aW5oOnNwb290cw==
                                                    [HTTP_ACCEPT] =&gt; application/json, text/javascript, */*; q=0.01
                                                    [HTTP_ORIGIN] =&gt; http://redup.triploader.com
                                                    [HTTP_X_REQUESTED_WITH] =&gt; XMLHttpRequest
                                                    [HTTP_USER_AGENT] =&gt; Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
                                                    [HTTP_CONTENT_TYPE] =&gt; application/x-www-form-urlencoded; charset=UTF-8
                                                    [HTTP_REFERER] =&gt; http://redup.triploader.com/groups/profile/508/madrid
                                                    [HTTP_ACCEPT_ENCODING] =&gt; gzip, deflate
                                                    [HTTP_ACCEPT_LANGUAGE] =&gt; es-ES,es;q=0.8,en;q=0.6
                                                    [HTTP_COOKIE] =&gt; __uvt=; Elgg=j53js4mmjeorub6q86ub7tkol7; uvts=3jBrh1Sf4SEXVHxA
                                                    [PHP_SELF] =&gt; /index.php
                                                    [PHP_AUTH_USER] =&gt; devinh
                                                    [PHP_AUTH_PW] =&gt; spoots
                                                    [REQUEST_TIME_FLOAT] =&gt; 1455712949.327
                                                    [REQUEST_TIME] =&gt; 1455712949`

**Comment by jdalsem** [comment] 2016-02-17 13:08
@insideth do you have steps to reproduce the problem?

**Comment by insideth** [comment] 2016-02-17 15:47
@jdalsem I´ve done more tests and is a conflict with group_tools plugin, if I disable this plugin add widgets function works ok. I also tried changing the order of both plugins but problem persists. 
I use group_tools 5.0 version.

**Comment by oseg** [comment] 2016-02-18 09:08
@jdalsem: Sorry for answering so late, I was very busy those days.

1. It is not a javascript loading issue: I waited a few seconds betweens the clicks, but I still reproduce the issue
2. It is not related to group_tools plugin: I installed a stock Elgg (v1.12.8) on my xampp with only widget manager as a custom plugin and I reproduce the issue

I have got a simpler scenario:
- In the widget manager settings, Set "use Widget Manager custom index": "for all users"
- On the index page, add the "activity widget" (for instance) to reproduce the issue

I also noticed that the issue is NOT reproduced on the user profile page: widget add/remove operations are working fine.

And last, but not least, I had a look in the php_error_log and I have got the following exception:
[18-Feb-2016 10:04:47 Europe/Berlin] Exception #1455786287: exception 'IOException' with message 'Failed to load new ElggObject for GUID: 49' in C:\xampp\htdocs\elgg-1.12.8\engine\classes\ElggObject.php:80
Stack trace:
#0 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\Database\EntityTable.php(100): ElggObject->__construct(Object(stdClass))
#1 C:\xampp\htdocs\elgg-1.12.8\engine\lib\entities.php(372): Elgg\Database\EntityTable->rowToElggStar(Object(stdClass))
#2 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\Database\EntityTable.php(660): entity_row_to_elggstar(Object(stdClass))
#3 C:\xampp\htdocs\elgg-1.12.8\engine\lib\entities.php(509): Elgg\Database\EntityTable->fetchFromSql('SELECT DISTINCT...', NULL)
#4 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\Database\EntityTable.php(471): _elgg_fetch_entities_from_sql('SELECT DISTINCT...', NULL)
#5 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\Database\EntityTable.php(174): Elgg\Database\EntityTable->getEntities(Array)
#6 C:\xampp\htdocs\elgg-1.12.8\engine\lib\entities.php(383): Elgg\Database\EntityTable->get(49)
#7 C:\xampp\htdocs\elgg-1.12.8\engine\classes\ElggEntity.php(1731): get_entity(49)
#8 C:\xampp\htdocs\elgg-1.12.8\engine\classes\ElggObject.php(159): ElggEntity->update()
#9 C:\xampp\htdocs\elgg-1.12.8\engine\classes\ElggEntity.php(1590): ElggObject->update()
#10 C:\xampp\htdocs\elgg-1.12.8\mod\widget_manager\lib\events.php(89): ElggEntity->save()
#11 [internal function]: widget_manager_create_object_handler('create', 'object', Object(ElggWidget))
#12 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\EventsService.php(56): call_user_func_array('widget_manager_...', Array)
#13 C:\xampp\htdocs\elgg-1.12.8\engine\classes\ElggEntity.php(1594): Elgg\EventsService->trigger('create', 'object', Object(ElggWidget))
#14 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\WidgetsService.php(94): ElggEntity->save()
#15 C:\xampp\htdocs\elgg-1.12.8\engine\lib\widgets.php(39): Elgg\WidgetsService->createWidget(1, 'index_activity', 'index', NULL)
#16 C:\xampp\htdocs\elgg-1.12.8\actions\widgets\add.php(27): elgg_create_widget(1, 'index_activity', 'index')
#17 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\ActionsService.php(88): include('C:\\xampp\\htdocs...')
#18 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\ActionsService.php(70): Elgg\ActionsService::includeFile('C:/xampp/htdocs...')
#19 C:\xampp\htdocs\elgg-1.12.8\engine\lib\actions.php(20): Elgg\ActionsService->execute('widgets/add')
#20 [internal function]: _elgg_action_handler(Array, 'action')
#21 C:\xampp\htdocs\elgg-1.12.8\engine\classes\Elgg\Router.php(80): call_user_func('_elgg_action_ha...', Array, 'action')
#22 C:\xampp\htdocs\elgg-1.12.8\index.php(60): Elgg\Router->route(Object(Elgg\Http\Request))
#23 {main}

**Comment by insideth** [comment] 2016-02-19 07:10
@oseg @jdalsem I tested disabling group_tools plugin on two different 1.12.8 installations and for me is the cause of the problem.

**Comment by EmJotGeh** [comment] 2016-05-22 00:22
same problem with my Elgg installation (2.1.1) on all pages (profile,groups etc) but when i'm disable the group_tools the problem is not solved!

**Comment by jdalsem** [comment] 2016-05-31 12:14
Could this be related to this fix? https://github.com/ColdTrick/widget_manager/commit/7686c749ba460d3dc0e0bcd3d42f4307da152ef7. You can test by manually performing the fix in your own installation...

**Comment by oseg** [comment] 2016-05-31 15:04
I integrated the above fix in widget manager v5.2 and tested it under elgg v1.12.8 and...
YES !!! That's it ! I do not reproduce the issue ! Good job, guys !

**Comment by EmJotGeh** [comment] 2016-05-31 18:41
This fix don't work for me. (elgg 2.1.1 - WidgetManager 6.0)

**Comment by jdalsem** [comment] 2016-06-01 06:58
@EmJotGeh maybe you have a different problem... can you tell me yours?

**Comment by EmJotGeh** [comment] 2016-06-01 13:01
I'm sorry but perhaps I should create a new topic for this.. 
When i activate the WidgetManager, the lightbox does not open and I can't add any widget to the site. I use the feedback plugin too and it's the same with this one it does not open. It looks like all ajax elements don't work. If I deactivate the WM all works fine.

**Comment by oseg** [comment] 2016-06-06 08:35
@EmJotGeh it seems to be a different issue: in my case the WM lightbox opened, but the problem happened after clicking the widget add button
@jdalsem Would you provide a minor release (v5.2.1) with bug fixes for v5.2 branch on github.com and/or elgg.org?

**Comment by EmJotGeh** [comment] 2016-06-08 18:33
Ok, i test it with WM 6.1 and the "add Widget" Button works again, but the Feedback Button (plugin) don't open. If i disable WM 6.1 the Feedback Button open again..?

**Comment by jdalsem** [comment] 2016-06-09 06:41
@EmJotGeh do you see any javascript warnings?

**Comment by EmJotGeh** [comment] 2016-06-13 17:31
Ok today I wanna look for any javascript warnings. It works, so that I think i forgot to clear the cache after the update. Thank you for your help! :-)

**Comment by jdalsem** [comment] 2016-06-13 19:14
Closing the issue as the original problem has been resolved

**Closed by jdalsem** 2016-06-13 19:14 UTC
