### ISSUE TITLE
Embed content not working in widgets

### ISSUE THREAD

**Issue by oseg** [ColdTrick/widget_manager#110] opened 2018-03-15 10:13 UTC
Context: elgg v2.3.3 + widget_manager v8.2 + widget_pack v1.3

Scenario:
- Add a "FreeHTML" widget to a group profile
- Click on the widget gear to configure FreeHTML widget
- Click on "embed content" link
- Select the file to embed
=> both embed popup and configure widget popup are dismissed
=> the selected file page is displayed

**Comment by jdalsem** [comment] 2019-04-16 09:16
This is also a problem in the latest Elgg 3 versions of the plugins

**Comment by jdalsem** [comment] 2019-04-16 09:53
Closing this as a duplicate of https://github.com/ColdTrick/embed_extended/issues/16

**Closed by jdalsem** 2019-04-16 09:53 UTC
